In [14]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('StudentsPerformance.csv')

In [16]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [17]:
df.corr(numeric_only=True) #To get only the Numerical Column

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [ ]:
X = df[['']]