In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [34]:
data = {
    # "Dept":["ML","DL","DL","Ml","DL","ML","DL","DL","Ml","DL"],
    "City" : ["Banglore","Vellore","Chennai","Banglore","Madurai","Banglore","Vellore","Chennai","Banglore","Madurai"],
    "Product" : ["Mobile","Clothing","Sandals","Electronics","Clothing","Sandals","Mobile","Clothing","Appliances","Furnichers"],
    "Price" : [2000,1000,4000,3000,1000,2000,1000,4000,3000,1000]
}

In [35]:
df = pd.DataFrame(data)

# Scenario 1

**Assigning X and Y**

In [36]:
x = df.drop(columns='Price')
y = df['Price']

In [37]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [38]:
encoder = TargetEncoder(handle_unknown='value',cols=['City','Product'])

In [39]:
encoder.fit_transform(xtrain,ytrain)

          City      Product
5  2262.872105  2356.388299
0  2262.872105  2143.611701
7  2498.239364  2285.462766
2  2498.239364  2356.388299
9  2072.686169  2087.364407
4  2072.686169  2285.462766
3  2262.872105  2347.581356
6  2087.364407  2143.611701

In [40]:
encoder.transform(xtest)

          City      Product
8  2262.872105  2250.000000
1  2087.364407  2285.462766

# Scenario 2

In [41]:
d = {
    "Dept":["ML","DL","DL","Ml","DL","ML","DL","DL","Ml","DL"],
    "Job" : ["Devops","Data Analyst","AI Engineer","Agents","ML Engineer","Devops","Data Analyst","AI Engineer","Agents","ML Engineer"],
    "Target" : ["OK","Good","Too Good","OK","Too Good","OK","Good","Too Good","OK","Too Good"]
 }

In [42]:
df = pd.DataFrame(d)

In [43]:
x = df.drop(columns='Target')
y = df['Target']

In [44]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [45]:
encoder = TargetEncoder()

In [46]:
encoder.fit_transform(xtrain[["Dept","Job"]],ytrain)

       Dept       Job
5  1.321806  1.321806
0  1.321806  1.321806
7  1.416046  1.463657
2  1.416046  1.463657
9  1.416046  1.463657
4  1.416046  1.463657
3  1.326209  1.326209
6  1.416046  1.196101

In [47]:
encoder.transform(xtest)

       Dept       Job
8  1.326209  1.326209
1  1.416046  1.196101